
services:
  rvc2mqtt:
    image: ghcr.io/dbergl/rvc2mqtt:latest
    #image: rvc2mqtt:tempf
    depends_on:
      - mosquitto
    environment:
      - CAN_INTERFACE_NAME=${RVC_CAN_INTERFACE_NAME}
      - FLOORPLAN_FILE_1=${RVC_FLOORPLAN_FILE_1}
      - LOG_CONFIG_FILE
      - MQTT_HOST
      - MQTT_PORT
      - MQTT_USERNAME
      - MQTT_PASSWORD
      - MQTT_CLIENT_ID
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - ./floorplan:/floorplan
      - ./configs/logger.yml.example:/config/logger.yml
      - ./logs:/logs

  can2mqtt:
    image: ghcr.io/dbergl/can2mqtt:latest
    depends_on:
      - mosquitto
    environment:
      - CAN_INTERFACE_NAME=${CANBUS_CAN_INTERFACE_NAME}
      - CONFIG_FILE=${CANBUS_CONFIG_FILE}
      - LOG_LEVEL
      - MQTT_HOST
      - MQTT_PORT
      - MQTT_USERNAME
      - MQTT_PASSWORD
      - MQTT_CLIENT_ID
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - ./configs/config.json:/config/config.json

  mosquitto:
    image: eclipse-mosquitto:2.0.18-openssl
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./logs/mosquitto:/mosquitto/log
      - ./data:/mosquitto/data
      - ./configs/mosquitto.conf:/mosquitto/config/mosquitto.conf
