
services:
  rvc2mqtt:
    image: ghcr.io/dbergl/rvc2mqtt:latest
    depends_on:
      - mosquitto
    environment:
      - CAN_INTERFACE_NAME=${RVC_CAN_INTERFACE_NAME:-can_rvc}
      - FLOORPLAN_FILE_1=/floorplan/floorplan.yml
      - LOG_CONFIG_FILE=/config/${RVC_LOG_CONFIG_FILE}
      - MQTT_HOST=${MQTT_HOST:-localhost}
      - MQTT_PORT=${MQTT_PORT:-1883}
      - MQTT_USERNAME
      - MQTT_PASSWORD
      - MQTT_CLIENT_ID
      - MQTT_TOPIC_BASE=${MQTT_TOPIC_BASE:-rvc}
    network_mode: "host"
    restart: on-failure:10
    volumes:
      - ./configs/rvc2mqtt/${RVC_FLOORPLAN_FILE:-2021-2024_swift-ethos-launch-terrain.yml}:/floorplan/floorplan.yml
      - ./configs/rvc2mqtt:/config
      - ./rvc-logs:/logs

  can2mqtt:
    image: ghcr.io/dbergl/can2mqtt:latest
    depends_on:
      - mosquitto
    environment:
      - CAN_INTERFACE_NAME=${CANBUS_CAN_INTERFACE_NAME:-can_bms}
      - CONFIG_FILE=/config/config.json
      - LOG_LEVEL=${CAN_LOG_LEVEL:-INFO}
      - MQTT_HOST=${MQTT_HOST:-localhost}
      - MQTT_PORT=${MQTT_PORT:-1883}
      - MQTT_USERNAME
      - MQTT_PASSWORD
      - MQTT_CLIENT_ID
    network_mode: "host"
    restart: on-failure:10
    volumes:
      - ./configs/can2mqtt/${CANBUS_CONFIG_FILE:-config.json}:/config/config.json

  modbus2mqtt:
    image: ghcr.io/dbergl/modbus2mqtt:latest
    depends_on:
      - mosquitto
    environment:
      - RTU=${RTU:-/dev/ttyUSB0}
      - CONFIG_FILE=/config/modbus2mqtt.csv
      - LOG_LEVEL=${MODBUS_LOG_LEVEL:-3}
      - MQTT_HOST=${MQTT_HOST:-mosquitto}
      - MQTT_PORT=${MQTT_PORT:-1883}
      - MQTT_USERNAME
      - MQTT_PASSWORD
      - MQTT_CLIENT_ID
    restart: on-failure:10
    device_cgroup_rules:
      - 'c 188:* rmw'
    volumes:
      - ./configs/modbus2mqtt/${MODBUS_CONFIG_FILE:-jayco.csv}:/config/modbus2mqtt.csv
      - /run/udev:/run/udev:ro
      - /dev:/dev

  node-red:
    image: nodered/node-red:latest
    depends_on:
      - mosquitto
    environment:
      - TZ=America/Los_Angeles
    ports:
      - "1880:1880"
    restart: on-failure:10
    volumes:
      - ./node-red-data:/data

  mosquitto:
    image: eclipse-mosquitto:2.0.18-openssl
    restart: on-failure:10
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./logs/mosquitto:/mosquitto/log
      - ./mosquitto-data:/mosquitto/data
      - ./configs/mosquitto:/mosquitto/config

  influxdb:
    profiles: [influx]
    image: influxdb:2
    restart: on-failure:10
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb-data:/var/lib/influxdb2
      - ./configs/influxdb:/etc/influxdb2

  telegraf:
    profiles: [influx]
    image: telegraf
    restart: on-failure:10
    depends_on:
      - influxdb
    environment:
      - INFLUX_TOKEN
    volumes:
      - ./configs/telegraf:/etc/telegraf
