
services:
  rvc2mqtt:
    image: ghcr.io/dbergl/rvc2mqtt:latest
    depends_on:
      - mosquitto
    environment:
      - CAN_INTERFACE_NAME=${RVC_CAN_INTERFACE_NAME}
      - FLOORPLAN_FILE_1=${RVC_FLOORPLAN_FILE_1}
      - LOG_CONFIG_FILE
      - MQTT_HOST=localhost
      - MQTT_PORT=1883
      - MQTT_USERNAME
      - MQTT_PASSWORD
      - MQTT_CLIENT_ID
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - ./floorplan:/floorplan
      - ./config:/config
      - ./logs:/home/worker/logs

  can2mqtt:
    image: ghcr.io/dbergl/can2mqtt:latest
    depends_on:
      - mosquitto
    container_name: can2mqtt
    environment:
      - CAN_INTERFACE_NAME=${CANBUS_CAN_INTERFACE_NAME}
      - CONFIG_FILE=${CANBUS_CONFIG_FILE}
      - MQTT_HOST=localhost
      - MQTT_PORT=1883
      - MQTT_USERNAME
      - MQTT_PASSWORD
      - MQTT_CLIENT_ID
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - ./config/config.json:/app/config.json

  mosquitto:
    image: eclipse-mosquitto:2.0.18-openssl
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./logs:/mosquitto/log
      - ./data:/mosquitto/data
      - ./config:/mosquitto/config
