# MQTT Automations
# Constrains: [ Mqtt, Cron ]
# Actions:    [ Mqtt, Http ]

- Name: Send password
  Mode: AND
  Constraints:
    - Mqtt : modbus/inverter/connected == True
  Actions:
    - Mqtt : modbus/inverter/set/password = 255 (Retained 0)

# modbus/inverter/set/5a
- Name: 5A charge
  Mode: AND
  Constraints:
    - Mqtt : modbus/inverter/set/5a != 0 (BlockRetained 1)
  Actions:
    - Mqtt : modbus/inverter/set/onoff = 1 (Retained 0)
    - Mqtt : modbus/inverter/set/current = 50 (Retained 0)
    - Mqtt : modbus/inverter/set/chargevolts = {{.Value}} (Retained 0)
    - Mqtt : modbus/inverter/set/5a = 0 (Retained 0)

# modbus/inverter/set/15a
- Name: 15A charge
  Mode: AND
  Constraints:
    - Mqtt : modbus/inverter/set/15a != 0 (BlockRetained 1)
  Actions:
    - Mqtt : modbus/inverter/set/onoff = 1 (Retained 0)
    - Mqtt : modbus/inverter/set/current = 150 (Retained 0)
    - Mqtt : modbus/inverter/set/chargevolts = {{.Value}} (Retained 0)
    - Mqtt : modbus/inverter/set/15a = 0 (Retained 0)

# modbus/inverter/set/20a
- Name: 20A charge
  Mode: AND
  Constraints:
    - Mqtt : modbus/inverter/set/20a != 0 (BlockRetained 1)
  Actions:
    - Mqtt : modbus/inverter/set/onoff = 1 (Retained 0)
    - Mqtt : modbus/inverter/set/current = 200 (Retained 0)
    - Mqtt : modbus/inverter/set/chargevolts = {{.Value}} (Retained 0)
    - Mqtt : modbus/inverter/set/20a = 0 (Retained 0)

# modbus/inverter/set/30a
- Name: 30A charge
  Mode: AND
  Constraints:
    - Mqtt : modbus/inverter/set/30a != 0 (BlockRetained 1)
  Actions:
    - Mqtt : modbus/inverter/set/onoff = 1 (Retained 0)
    - Mqtt : modbus/inverter/set/current = 400 (Retained 0)
    - Mqtt : modbus/inverter/set/chargevolts = {{.Value}} (Retained 0)
    - Mqtt : modbus/inverter/set/30a = 0 (Retained 0)
