# MQTT Automations 
# Constrains: [ Mqtt, Cron ]
# Actions:    [ Mqtt, Http ]

- Name: Interior lights on
  Mode: AND
  Constraints:
    - Mqtt : rvc/set/lights/int/all == on
  Actions:
    - Mqtt : rvc/set/lights/int/main = on
    - Mqtt : rvc/set/lights/int/livingohc = on
    - Mqtt : rvc/set/lights/int/kitchenohc = on
    - Mqtt : rvc/set/lights/int/bunk = on
    - Mqtt : rvc/set/lights/int/bed = on
    - Mqtt : rvc/set/lights/int/bath = on
    - Mqtt : rvc/state/lights/int/all = on 
    - Mqtt : rvc/set/lights/int/all = 

- Name: Interior lights off
  Mode: AND
  Constraints:
    - Mqtt : rvc/set/lights/int/all == off
  Actions:
    - Mqtt : rvc/set/lights/int/main = off
    - Mqtt : rvc/set/lights/int/livingohc = off
    - Mqtt : rvc/set/lights/int/kitchenohc = off
    - Mqtt : rvc/set/lights/int/bunk = off
    - Mqtt : rvc/set/lights/int/bed = off
    - Mqtt : rvc/set/lights/int/bath = off
    - Mqtt : rvc/set/lights/int/all = 

- Name: Exterior lights on
  Mode: AND
  Constraints:
    - Mqtt : rvc/set/lights/ext/all == on
  Actions:
    - Mqtt : rvc/set/lights/ext/awning = on
    - Mqtt : rvc/set/lights/ext/step = on
    - Mqtt : rvc/set/lights/ext/all = 

- Name: Exterior lights off
  Mode: AND
  Constraints:
    - Mqtt : rvc/set/lights/ext/all == off
  Actions:
    - Mqtt : rvc/set/lights/ext/awning = off
    - Mqtt : rvc/set/lights/ext/step = off
    - Mqtt : rvc/set/lights/ext/all = 

