# MQTT Automations 
# Constrains: [ Mqtt, Cron ]
# Actions:    [ Mqtt, Http ]

- Name: Tank Heaters On
  Mode: AND
  Constraints:
    - Mqtt : rvc/set/tanks/all/heater == on
  Actions:
    - Mqtt : rvc/set/tanks/black/heater = on
    - Mqtt : rvc/set/tanks/fresh/heater = on
    - Mqtt : rvc/set/tanks/gray/heater = on
    - Mqtt : rvc/set/tanks/gray2/heater = on
    - Mqtt : rvc/state/tanks/all/heater = on
    - Mqtt : rvc/set/tanks/all/heater = (BlockRetained 1)

- Name: Tank Heaters Off
  Mode: AND
  Constraints:
    - Mqtt : rvc/set/tanks/all/heater == off
  Actions:
    - Mqtt : rvc/set/tanks/black/heater = off
    - Mqtt : rvc/set/tanks/fresh/heater = off
    - Mqtt : rvc/set/tanks/gray/heater = off
    - Mqtt : rvc/set/tanks/gray2/heater = off
    - Mqtt : rvc/state/tanks/all/heater = off
    - Mqtt : rvc/set/tanks/all/heater = (BlockRetained 1)

- Name: Ensure Tank Heaters status is correct
  Mode: OR
  Constraints:
    - Mqtt : rvc/state/tanks/black/heater == on
    - Mqtt : rvc/state/tanks/fresh/heater == on
    - Mqtt : rvc/state/tanks/gray/heater == on
    - Mqtt : rvc/state/tanks/gray2/heater == on
  Actions:
    - Mqtt : rvc/state/tanks/all/heater = on

- Name: Ensure Tank Heaters status is correct
  Mode: AND
  Constraints:
    - Mqtt : rvc/state/tanks/black/heater == off
    - Mqtt : rvc/state/tanks/fresh/heater == off
    - Mqtt : rvc/state/tanks/gray/heater == off
    - Mqtt : rvc/state/tanks/gray2/heater == off
  Actions:
    - Mqtt : rvc/state/tanks/all/heater = off

