# MQTT Automations 
# Constrains: [ Mqtt, Cron ]
# Actions:    [ Mqtt, Http ]

- Name: Shut off waterpump after 15 min
  Mode: AND
  Delay: 15m
  Constraints:
    - Mqtt : rvc/set/waterpump/autooff == on
    - Mqtt : rvc/state/waterpump == on
  Actions:
    - Mqtt : rvc/set/waterpump = off

